#!/bin/bash

hourly_user=`/sbin/ifconfig | /bin/grep ppp | /usr/bin/wc -l`
LOGDIR=~/log
DATE=`date +"%Y%m%d"`
TIME=`date +"%H%M%S"`
if [ ! -d $LOGDIR ]; then
	mkdir $LOGDIR
fi
if [ ! -f ${LOGDIR}/hourly_user.txt ]; then
	echo "Date		Time		Total" > ${LOGDIR}/hourly_user.txt
fi

echo "${DATE}	${TIME}		${hourly_user}" >> ${LOGDIR}/hourly_user.txt
echo "${DATE}	${TIME}		${hourly_user}"
