#!/bin/bash

hourly_user=`/sbin/ifconfig | /bin/grep ppp | /usr/bin/wc -l`
LOGDIR=~/log
LOGFILE=hourly_user.log
DATE=`date +"%Y%m%d"`
TIME=`date +"%H%M%S"`
if [ ! -d $LOGDIR ]; then
	mkdir $LOGDIR
fi
if [ ! -f ${LOGDIR}/${LOGFILE} ]; then
	echo "Date		Time		Total" > ${LOGDIR}/${LOGFILE}
fi

echo "${DATE}	${TIME}		${hourly_user}" >> ${LOGDIR}/${LOGFILE}
echo "${DATE}	${TIME}		${hourly_user}"
