#!/bin/bash
if [ "$#" -ne 1 ]
then
	echo "Need to provide a username, such as public"
	exit 1
fi
timestamp=`date +"%H-%M-%S"`
filename="${1}+${timestamp}.tmp"
logname="/var/log/syslog"
last -w $1 | grep -n ppp > $filename
totalRx=0
totalTx=0

while read loginInstance 
do
	pppid=`echo $loginInstance | awk '{print $2;}'`
	stat=`echo $loginInstance | awk '{print $9;}'`
#	echo $loginInstance
	if [ "$stat" == "logged" ]
	then
		Rx=`ifconfig $pppid | grep "RX bytes" | awk '{print $2;}' | sed 's/.*://'`
		Tx=`ifconfig $pppid | grep "RX bytes" | awk '{print $6;}' | sed 's/.*://'`
	else
		month=`echo $loginInstance | awk '{print $5;}'`
		day=`echo $loginInstance | awk '{print $6;}'`
		time=`echo $loginInstance | awk '{print $7;}'`
		sessionline=`grep -n $time $logname | grep "$month $day" | grep $pppid | head -n 2 | tail -n 1`
		if [ "$sessionline" == "" ]
		then
			linenum=`grep -n $time $logname | grep "$month $day" | head -n 1 | awk -F: '{print $1;}'`
			sessionline=`head -n $linenum $logname | grep -n $pppid | tail -n 1`
		fi
		linenum=`echo $sessionline | awk -F: '{print $1;}'`
		sessionid=`echo $sessionline | awk '{print $5;}' | sed 's/.*\[\([^]]*\)\].*/\1/g'`
		Tx=`tail -n +${linenum} $logname | grep $sessionid | grep Sent | head -n 1 | awk '{print $7}'`
		Rx=`tail -n +${linenum} $logname | grep $sessionid | grep Sent | head -n 1 | awk '{print $10}'`
	fi
	totalRx=$((${totalRx} + ${Rx}))	
	totalTx=$((${totalTx} + ${Tx}))	
	
done < $filename

echo Received:	${totalRx} bytes.	Sent:	${totalTx} bytes.
rm ${filename}
